[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:local"

[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android:local"

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:local"

[target.armv7-linux-androideabi]
image = "ghcr.io/cross-rs/armv7-linux-androideabi:local"

[target.armv7-linux-androideabi.env]
passthrough = ["CROSS_CONTAINER_ENGINE_NO_BUILDKIT=1"]

[target.aarch64-linux-android.env]
passthrough = ["CROSS_CONTAINER_ENGINE_NO_BUILDKIT=1"]

[target.aarch64-linux-android]
passthrough = ["CROSS_CONTAINER_ENGINE_NO_BUILDKIT=1"]

[target.i686-linux-android]
passthrough = ["CROSS_CONTAINER_ENGINE_NO_BUILDKIT=1"]
