[target.aarch64-linux-android]
image = 'aarch64-linux-android:with-zmq'

[target.armv7-linux-androideabi]
image = 'armv7-linux-androideabi:with-zmq'

[target.i686-linux-android]
image = 'i686-linux-android:with-zmq'

[target.x86_64-linux-android]
image = 'x86_64-linux-android:with-zmq'
