name: 'Indy-VDR'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish-binaries:
        description: 'Publish Binaries to Release (will create a release if no release exits for branch or tag)'
        required: true
        default: false
        type: boolean
      publish-wrappers:
        description: 'Publish Wrappers to Registries'
        required: true
        default: false
        type: boolean

jobs:
  build-android:
    name: Build library (Android)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          [
            aarch64-linux-android,
            armv7-linux-androideabi,
            i686-linux-android,
            x86_64-linux-android,
          ]

    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/cross-rs/cross.git
          cd cross
          git submodule update --init --recursive
          cargo build-docker-image ${{matrix.architecture}}  \
             --build-arg ANDROID_NDK=r24 \
             --build-arg ANDROID_SDK=21 \
             --build-arg ANDROID_VERSION=5.0.0_r1
      - run: |
          cargo install --bins --git https://github.com/rust-embedded/cross --tag v0.2.4 cross
          cross build --release --target ${{matrix.architecture}} --package indy-vdr
      - name: Save library
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.architecture}}
          path: target/${{ matrix.architecture }}/release/libindy_vdr.so

  create-android-library:
    name: Create library (Android)
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Fetch libraries
        uses: actions/download-artifact@v3
      - run: |
          sudo mkdir ./libs
          sudo mv aarch64-linux-android   ./libs/arm64-v8a
          sudo mv armv7-linux-androideabi ./libs/armeabi-v7a
          sudo mv i686-linux-android      ./libs/x86
          sudo mv x86_64-linux-android    ./libs/x86_64
      - name: Save Android library
        uses: actions/upload-artifact@v3
        with:
          name: android-libraries
          path: ./libs
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            aarch64-linux-android
            armv7-linux-androideabi
            i686-linux-android
            x86_64-linux-android
          failOnError: false
